@WebAPINorthWind_HostAddress = http://localhost:5096

GET {{WebAPINorthWind_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebAPINorthWind_HostAddress}}/weatherforecast

###

GET {{WebAPINorthWind_HostAddress}}/api/category

###

PUT {{WebAPINorthWind_HostAddress}}/api/category
Content-Type: application/json

{
  //Category
}

###
